### ISSUE TITLE
The keep-exp flag is not compatible with PerWorldInventory

### ISSUE THREAD

**Issue by TheoRetisch1** [Invvk/WorldGuardExtraFlags#16]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

The keep-exp flag doesn't work together with the PerWorldInventory plugin. If you die in a corresponding region, the EXP are simply reseted. But if the flag keep-inventory is active at the same time, the EXP will also be restored.

### To Reproduce

1. Install Worldguard + WorldguardExtraFlags + PerWorldInventory
2. Create a region.
3. Set the the flag keep-exp to true for the region.
4. Die inside the region -> you will lose your EXP
5. Try it without PWI -> you will keep your EXP

### Expected behaviour

In a region with kee-exp flag enabled, exp should be preserved on death even if perworldinventory is enabled.

### Error log (if applicable)

There are no errors in the log.

### WGEF-Reborn version

WGEF-Reborn version 2.1.6

### Checklist

- [X] I'm using java 16+ and running my server in 1.17.1+
- [X] I am using the newest build from https://github.com/Invvk/WorldGuardExtraFlagsPlugin/releases and the issue still persists.

### Anything else?

PerWorldInventory 2.3.2 (https://github.com/EbonJaeger/perworldinventory-kt)
PWI config: https://pastebin.com/yfpPm43N
PWI world settings: https://pastebin.com/hMeGkixm

Since PerWorldInventory is a widely used inventory management plugin,  it would be great if it would be compatible. Is this a bug that you can fix or does this issue need to be resolved on PerworldInventory's end?

**Comment by Invvk** [comment]
The thing is, I'm not really sure that I can do anything because I'm already querying the flags according to the world that the player is currently in, not just the coordinates. The issue could be due to event execution priority. I've looked into the api that PWI is providing and I can't find anything that could help with this matter. I will investigate the issue further to see if I can do anything, but I can't really promise that I will be able to fix it.

**Comment by Invvk** [comment]
unable to replicate the issue, it seems that it is working fine with PWI 2.3.2

**Comment by Invvk** [comment]
I was able to replicate the issue. However, all of my attempts to fix the issue, including setting the exp and levels manually failed so far. I tried to change event priority but without any success. I'm sorry but I don't think I will be able to fix this issue

**Comment by TheoRetisch1** [comment]
Thanks for your quick reply and commitment! Have a nice day 👍

**Comment by Invvk** [comment]
I've looked inside the src of PWI in [this](https://github.com/EbonJaeger/perworldinventory-kt/blob/master/src/main/kotlin/me/ebonjaeger/perworldinventory/listener/player/PlayerDeathListener.kt#L29) line where he modifies the exp, if he checks for keepLevels is true like he is checking if keepInventory, in theory that would resolve the issue.

**Comment by Invvk** [comment]
can you try [this](https://github.com/Invvk/WorldGuardExtraFlags/releases/tag/2.1.7-SNAPSHOT) version for me ?

**Comment by TheoRetisch1** [comment]
Awesome, it works! How did you do it?

**Comment by TheoRetisch1** [comment]
Ahh I read your comment, thank you very much! 💯

**Comment by Invvk** [comment]
> 
> 
> Awesome, it works! How did you do it?

apparently, because the event priority in PWI is `MONITOR` meaning it will run last, and I noticed that in the source code it seemed that PWI developer was setting the exp and levels to `newExp` and `newLevel`. I moved my event priority back a bit making it run before PWI's event and I attempt to set `newExp` and `newLevel` with the player exp and level before death. it seems that it fixed the issue
